
[build-dependencies]

  [build-dependencies.tauri-build]
    features = []
    version = "1.2"

[dependencies]
  serde_json = "1.0"
  reqwest = { version = "0.11", features = ["json", "blocking"] }
  [dependencies.serde]
    features = ["derive"]
    version = "1.0"

  [dependencies.tauri]
    features = ["dialog-all", "fs-all", "path-all", "process-all", "shell-all"]
    version = "1.2"

[features]
  custom-protocol = ["tauri/custom-protocol"]

[package]
  authors = ["you"]
  description = "A Tauri App"
  edition = "2021"
  license = ""
  name = "prem-app"
  repository = ""
  version = "0.0.3"
